#!/usr/bin/env python3
"""Render content/settings.md from the server's setting definitions.

Every setting the server reads from the environment is declared once in
``SETTING_DEFINITIONS`` in server/app/settings.py. This script turns that
list into the Settings Reference page so the page can never drift from the
code. The page is committed so it reads on GitHub as well; run this after
changing a setting and commit the result. ``--check`` exits non-zero when the
committed page is stale, which is what the Docs workflow runs.

Only the standard library and the settings module itself are needed; the
server's dependencies are not imported.
"""

from __future__ import annotations

import argparse
import importlib.util
import os
import sys

DOCS = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REPO = os.path.dirname(DOCS)
SETTINGS_PY = os.path.join(REPO, "server", "app", "settings.py")
OUTPUT = os.path.join(DOCS, "content", "settings.md")

# Defaults that depend on where the server is installed; the table shows how
# they resolve instead of the path on the machine that rendered the page.
LOCATION_DEPENDENT = {
    "ui_path": "`app/ui` inside the installed package, else `<repo>/client/dist/ui`",
    "template_schema_path": "`template_schema.yml` next to the server package",
}

HEADER = """---
title: Settings Reference
description: Every environment variable the SealSkin server reads, with its default.
---

<!-- Generated by docs/scripts/generate-settings-doc.py from server/app/settings.py. Do not edit by hand. -->

Every setting is read once at start-up from an environment variable named
`SEALSKIN_<NAME>`. Booleans accept `true`, `1` or `yes` (anything else is
false); an unparsable integer falls back to the default with an error in the
log. When the server runs in the
[linuxserver/sealskin](https://github.com/linuxserver/docker-sealskin)
container the defaults already point at the `/config` and `/storage` volumes,
so most installations set none of these.

`HOST_URL` is the one variable without the prefix: it is read by the
first-run admin bootstrap and written into `/config/admin.json` as the
server address. See [Configuration](configuration.md) for the files these
paths refer to.

| Variable | Type | Default | Description |
| --- | --- | --- | --- |
"""


def load_definitions() -> list[dict]:
    """Import settings.py in isolation and return SETTING_DEFINITIONS."""
    # settings.py imports `.version` relative to the `app` package; load the
    # package by path so the server's other modules stay untouched.
    pkg_dir = os.path.dirname(SETTINGS_PY)
    spec = importlib.util.spec_from_file_location(
        "app", os.path.join(pkg_dir, "__init__.py"), submodule_search_locations=[pkg_dir]
    )
    module = importlib.util.module_from_spec(spec)
    sys.modules["app"] = module
    spec.loader.exec_module(module)
    from app.settings import SETTING_DEFINITIONS  # noqa: E402

    return SETTING_DEFINITIONS


def format_default(setting: dict) -> str:
    """Return the Markdown cell for a setting's default."""
    name = setting["name"]
    if name in LOCATION_DEPENDENT:
        return LOCATION_DEPENDENT[name]
    default = setting.get("default")
    if default is None or default == "":
        return "_(empty)_"
    if isinstance(default, bool):
        return f"`{'true' if default else 'false'}`"
    return f"`{default}`"


def render(definitions: list[dict]) -> str:
    """Render the full page."""
    rows = []
    for setting in definitions:
        name = f"`SEALSKIN_{setting['name'].upper()}`"
        stype = f"`{setting['type']}`"
        help_text = setting.get("help", "").replace("|", "\\|")
        rows.append(f"| {name} | {stype} | {format_default(setting)} | {help_text} |")
    return HEADER + "\n".join(rows) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if content/settings.md is stale")
    args = parser.parse_args()

    page = render(load_definitions())
    if args.check:
        try:
            with open(OUTPUT, encoding="utf-8") as handle:
                current = handle.read()
        except FileNotFoundError:
            current = ""
        if current != page:
            print(f"{os.path.relpath(OUTPUT, REPO)} is out of date; run docs/scripts/generate-settings-doc.py")
            return 1
        print(f"{os.path.relpath(OUTPUT, REPO)} is up to date")
        return 0

    with open(OUTPUT, "w", encoding="utf-8") as handle:
        handle.write(page)
    print(f"wrote {os.path.relpath(OUTPUT, REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
